name: modrinth
on:
  release:
    types: [ published ]

jobs:
  modrinth:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
      - uses: https://github.com/actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          check-latest: true
      - run: ./gradlew --no-daemon modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_PUBLISH }}