[versions]
minecraft = "26.2"
fabric-loader = "0.19.3"
cloth-config = "26.2.155"
modmenu = "20.0.0-beta.4"
jtoml = "1.5.2"
bouncycastle = "1.84"
zstd-jni = "1.5.7-11"
adventure-fabric = "7.1.0"
messaging-lib = "3.2.0"
expiring-map = "0.5.11"

java = "25"
self = "2.0.0"

loom = "1.17-SNAPSHOT"
minotaur = "2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

clothconfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
jtoml-configurate = { module = "io.github.wasabithumb:jtoml-configurate", version.ref = "jtoml" }

bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }

adventure-platform-fabric = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-fabric" }
messaginglib-fabric = { module = "land.chipmunk.code.kaboomstandardsorganization.messaginglib:fabric", version.ref = "messaging-lib" }

expiringmap = { module = "net.jodah:expiringmap", version.ref = "expiring-map" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
