[versions]
loom = "1.15-SNAPSHOT"
minecraft = "26.1"
fabric-loader = "0.18.4"
cloth-config = "21.11.153"
modmenu = "18.0.0-alpha.8"
jtoml = "1.5.1"
bouncycastle = "1.83"
zstd-jni = "1.5.7-7"
adventure-fabric = "6.8.0"
messaging-lib = "3.1.1-SNAPSHOT"
expiring-map = "0.5.11"

java = "25"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

clothconfig = { module = "me.shedaniel.cloth:cloth-config-fabric", version.ref = "cloth-config" }
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
jtoml-configurate = { module = "io.github.wasabithumb:jtoml-configurate", version.ref = "jtoml" }

bcprov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
zstd-jni = { module = "com.github.luben:zstd-jni", version.ref = "zstd-jni" }

adventure-platform-fabric = { module = "net.kyori:adventure-platform-fabric", version.ref = "adventure-fabric" }
messaginglib-fabric = { module = "land.chipmunk.code.kaboomstandardsorganization.messaginglib:fabric", version.ref = "messaging-lib" }

expiringmap = { module = "net.jodah:expiringmap", version.ref = "expiring-map" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
